### ISSUE TITLE
paper PDF

### ISSUE THREAD

**Issue by ThyrixYang** [Vekteur/quantile-recalibration-training#1]
Hi! 
Would you please provide a PDF version paper? I did not find your paper with google.

**Comment by ThyrixYang** [comment]
I find a typo in the README file, in citation: 
year      = {2043},

**Comment by Vekteur** [comment]
Hello! I just saw your issue. The paper is now available on [arXiv](https://arxiv.org/abs/2403.11964)! I fixed the typo, thanks! I also recently added a demo in the repository if you are interested.
